### ISSUE TITLE
How to install/run

### ISSUE THREAD

**Issue by ArchGalileu** [robrotheram/gogallery#54]
Tried to install but data "make" must provide all ir clear, but mine of them work.

Best regards
ArchGalileu

**Comment by robrotheram** [comment]
Hello, I do produce pre-compiled binaries in the releases. You can download them and put it in your path and run 
`gogallery` and it will launch the GUI. Or. if you prefer the Command line you can run `gogallery --help` so see all the options


To build from source requires the following prerequisites. 
go version 1.19+
node version 16+

and the go bin path in your path
```
export GOPATH="$HOME/go"
PATH="$GOPATH/bin:$PATH"

**Comment by wanghaisheng** [comment]
can we deploy on github pages

**Comment by robrotheram** [comment]
There is nothing stopping you from taking the build site and deploying it to GitHub pages 
I am not planning on building a github action type of thing similar to hugo due to the source images folder is generally too big 
According to the [docs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#repository-size-limits) GitHub only supports around < 5GB repositories
