### ISSUE TITLE
Password protected gallery

### ISSUE THREAD

**Issue by oplatek** [robrotheram/gogallery#63]
Hi,

I am a newbie to go and the gogallery; please be patient with my potentially naive questions.

I have two use cases for using the gallery.
1. Staticly hosting ~2GB of my photos (I am confused by the `gogallery serve` command). I do not to run the server, right? 
2. Staticly hosting 15GB of my photos behind a password?
   - Is a password-protected gallery supported?
   - Could https://github.com/robinmoisson/staticrypt be easily integrated?

Thank you very much. Gogallery looks like an awesome project, and it will probably give me an excuse to learn the go language.

**Comment by robrotheram** [comment]
Hi, sorry for the late reply. Thanks for having a look at gogallery, 
1. The `gogallery serve` is partly backwards compatibility, as the project started as a full webserver before transitioning to being a static site generator. Now its also used to "preview" the site without needing to render all the html pages. Its not required for building a static site. You can just do `gogallery build` and serve the html pages anywhere you like 

2. Currently password-protected is not supported but it is a interesting idea. I have not come across [staticrypt](https://github.com/robinmoisson/staticrypt) before looks interesting but not directly compatible since it uses it own JS CLI and gogallery uses golang template engine for rendering the html pages.  

There is nothing should stop you from using it on the output of gogallery build as 

Only concern I have is its a lot of data to encrypt and decrypt as I am unsure if staticcrypt is just doing the html pages and would leave the images unencrypted. which in my mind is a risk

**Comment by oplatek** [comment]
I found out that I can modify the Apache2 behavior to password-protect specific directories, i.e., the one with a statically built website using [.htaccess files](https://httpd.apache.org/docs/2.4/howto/htaccess.html).

Problem solved for me :)
